### ISSUE TITLE
Поиск перестает работать, если содержит в себе знак вопроса или решетку

### ISSUE THREAD

**Issue by realtoptuk** [reyohoho/reyohoho#1]
Если в поисковую строку ввести фильм, в котором содержится **знак вопроса** или **#**, то поиск упадет.

Ошибка **422 Unprocessable Content**

Как вариант, можно на фронте убрать такие символы чем-то вроде search.replaceAll(/#|\?/g, '')

Дополнительно: сейчас можно отправлять запросы на сервер при пустом значении. 

Я бы предложил дополнительно search.trim() использовать при обработке поиска и проверять на непустое значение.

Спасибо за отличный сервис.

**Comment by reyohoho** [comment]
Поправлено b0add9fa54c651af62cc1205744bd93becdee883
