### ISSUE TITLE
Add history save switch

### ISSUE THREAD

**Issue by MrPandir** [reyohoho/reyohoho#3]
Please add a button that will allow you to disable saving search history

**Comment by le-xot** [comment]
> Please add a button that will allow you to disable saving search history

I completely agree with this suggestion. Having a dedicated button for this feature would make it much easier for users to manage their privacy settings.

Thank you for considering this request!

**Comment by olegsvs** [comment]
Switch added 204c32ebf2475817155319e433205476a0ffa56d

**Comment by reyohoho** [comment]
Switch added 204c32ebf2475817155319e433205476a0ffa56d
